---
config:
  service:
    name: "master-service"
    version: 1.0.0
    address: localhost
    port: 8095
  hosts:
    cache:
      address: "localhost"
      port: 6379
    database:
      address: "localhost"
      name: master_db
      driver: postgre
      password: your_password
      port: 5432
      username: your_username
    broker:
      driver: "nats"
      address: "127.0.0.1"
      port: 4222
      username: ""
      password: ""
