// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pkg/user/proto/user.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	GetUsers(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error)
	GetUserById(ctx context.Context, in *GetUserByIDRequest, opts ...client.CallOption) (*GetUserByIDResponse, error)
	CreateUser(ctx context.Context, in *MutationUserRequest, opts ...client.CallOption) (*MutationUserResponse, error)
	UpdateUser(ctx context.Context, in *MutationUserRequest, opts ...client.CallOption) (*MutationUserResponse, error)
	UpdateUserPassword(ctx context.Context, in *MutationUserRequest, opts ...client.CallOption) (*MutationUserResponse, error)
	DeleteUser(ctx context.Context, in *MutationUserRequest, opts ...client.CallOption) (*MutationUserResponse, error)
	GetUserGroupbyRole(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*GetUserGroupByRoleResponse, error)
	ActivateUser(ctx context.Context, in *Empty, opts ...client.CallOption) (*MutationUserResponse, error)
	UserForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...client.CallOption) (*MutationUserResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetUsers(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUsers", in)
	out := new(GetUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserById(ctx context.Context, in *GetUserByIDRequest, opts ...client.CallOption) (*GetUserByIDResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserById", in)
	out := new(GetUserByIDResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreateUser(ctx context.Context, in *MutationUserRequest, opts ...client.CallOption) (*MutationUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.CreateUser", in)
	out := new(MutationUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateUser(ctx context.Context, in *MutationUserRequest, opts ...client.CallOption) (*MutationUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UpdateUser", in)
	out := new(MutationUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateUserPassword(ctx context.Context, in *MutationUserRequest, opts ...client.CallOption) (*MutationUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UpdateUserPassword", in)
	out := new(MutationUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeleteUser(ctx context.Context, in *MutationUserRequest, opts ...client.CallOption) (*MutationUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.DeleteUser", in)
	out := new(MutationUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserGroupbyRole(ctx context.Context, in *GetUserRequest, opts ...client.CallOption) (*GetUserGroupByRoleResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserGroupbyRole", in)
	out := new(GetUserGroupByRoleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) ActivateUser(ctx context.Context, in *Empty, opts ...client.CallOption) (*MutationUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.ActivateUser", in)
	out := new(MutationUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UserForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...client.CallOption) (*MutationUserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UserForgotPassword", in)
	out := new(MutationUserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	GetUsers(context.Context, *GetUserRequest, *GetUserResponse) error
	GetUserById(context.Context, *GetUserByIDRequest, *GetUserByIDResponse) error
	CreateUser(context.Context, *MutationUserRequest, *MutationUserResponse) error
	UpdateUser(context.Context, *MutationUserRequest, *MutationUserResponse) error
	UpdateUserPassword(context.Context, *MutationUserRequest, *MutationUserResponse) error
	DeleteUser(context.Context, *MutationUserRequest, *MutationUserResponse) error
	GetUserGroupbyRole(context.Context, *GetUserRequest, *GetUserGroupByRoleResponse) error
	ActivateUser(context.Context, *Empty, *MutationUserResponse) error
	UserForgotPassword(context.Context, *ForgotPasswordRequest, *MutationUserResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		GetUsers(ctx context.Context, in *GetUserRequest, out *GetUserResponse) error
		GetUserById(ctx context.Context, in *GetUserByIDRequest, out *GetUserByIDResponse) error
		CreateUser(ctx context.Context, in *MutationUserRequest, out *MutationUserResponse) error
		UpdateUser(ctx context.Context, in *MutationUserRequest, out *MutationUserResponse) error
		UpdateUserPassword(ctx context.Context, in *MutationUserRequest, out *MutationUserResponse) error
		DeleteUser(ctx context.Context, in *MutationUserRequest, out *MutationUserResponse) error
		GetUserGroupbyRole(ctx context.Context, in *GetUserRequest, out *GetUserGroupByRoleResponse) error
		ActivateUser(ctx context.Context, in *Empty, out *MutationUserResponse) error
		UserForgotPassword(ctx context.Context, in *ForgotPasswordRequest, out *MutationUserResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) GetUsers(ctx context.Context, in *GetUserRequest, out *GetUserResponse) error {
	return h.UserServiceHandler.GetUsers(ctx, in, out)
}

func (h *userServiceHandler) GetUserById(ctx context.Context, in *GetUserByIDRequest, out *GetUserByIDResponse) error {
	return h.UserServiceHandler.GetUserById(ctx, in, out)
}

func (h *userServiceHandler) CreateUser(ctx context.Context, in *MutationUserRequest, out *MutationUserResponse) error {
	return h.UserServiceHandler.CreateUser(ctx, in, out)
}

func (h *userServiceHandler) UpdateUser(ctx context.Context, in *MutationUserRequest, out *MutationUserResponse) error {
	return h.UserServiceHandler.UpdateUser(ctx, in, out)
}

func (h *userServiceHandler) UpdateUserPassword(ctx context.Context, in *MutationUserRequest, out *MutationUserResponse) error {
	return h.UserServiceHandler.UpdateUserPassword(ctx, in, out)
}

func (h *userServiceHandler) DeleteUser(ctx context.Context, in *MutationUserRequest, out *MutationUserResponse) error {
	return h.UserServiceHandler.DeleteUser(ctx, in, out)
}

func (h *userServiceHandler) GetUserGroupbyRole(ctx context.Context, in *GetUserRequest, out *GetUserGroupByRoleResponse) error {
	return h.UserServiceHandler.GetUserGroupbyRole(ctx, in, out)
}

func (h *userServiceHandler) ActivateUser(ctx context.Context, in *Empty, out *MutationUserResponse) error {
	return h.UserServiceHandler.ActivateUser(ctx, in, out)
}

func (h *userServiceHandler) UserForgotPassword(ctx context.Context, in *ForgotPasswordRequest, out *MutationUserResponse) error {
	return h.UserServiceHandler.UserForgotPassword(ctx, in, out)
}
