// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: proto/master-data/enum/enum.proto

package enum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnumService_GetEnums_FullMethodName    = "/enum.EnumService/GetEnums"
	EnumService_GetEnumById_FullMethodName = "/enum.EnumService/GetEnumById"
	EnumService_UpdateEnum_FullMethodName  = "/enum.EnumService/UpdateEnum"
)

// EnumServiceClient is the client API for EnumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnumServiceClient interface {
	GetEnums(ctx context.Context, in *GetEnumRequest, opts ...grpc.CallOption) (*GetEnumResponse, error)
	GetEnumById(ctx context.Context, in *GetEnumByIDRequest, opts ...grpc.CallOption) (*GetEnumByIDResponse, error)
	UpdateEnum(ctx context.Context, in *UpdateEnumRequest, opts ...grpc.CallOption) (*UpdateEnumResponse, error)
}

type enumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnumServiceClient(cc grpc.ClientConnInterface) EnumServiceClient {
	return &enumServiceClient{cc}
}

func (c *enumServiceClient) GetEnums(ctx context.Context, in *GetEnumRequest, opts ...grpc.CallOption) (*GetEnumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnumResponse)
	err := c.cc.Invoke(ctx, EnumService_GetEnums_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enumServiceClient) GetEnumById(ctx context.Context, in *GetEnumByIDRequest, opts ...grpc.CallOption) (*GetEnumByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnumByIDResponse)
	err := c.cc.Invoke(ctx, EnumService_GetEnumById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enumServiceClient) UpdateEnum(ctx context.Context, in *UpdateEnumRequest, opts ...grpc.CallOption) (*UpdateEnumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEnumResponse)
	err := c.cc.Invoke(ctx, EnumService_UpdateEnum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnumServiceServer is the server API for EnumService service.
// All implementations must embed UnimplementedEnumServiceServer
// for forward compatibility.
type EnumServiceServer interface {
	GetEnums(context.Context, *GetEnumRequest) (*GetEnumResponse, error)
	GetEnumById(context.Context, *GetEnumByIDRequest) (*GetEnumByIDResponse, error)
	UpdateEnum(context.Context, *UpdateEnumRequest) (*UpdateEnumResponse, error)
	mustEmbedUnimplementedEnumServiceServer()
}

// UnimplementedEnumServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnumServiceServer struct{}

func (UnimplementedEnumServiceServer) GetEnums(context.Context, *GetEnumRequest) (*GetEnumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnums not implemented")
}
func (UnimplementedEnumServiceServer) GetEnumById(context.Context, *GetEnumByIDRequest) (*GetEnumByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnumById not implemented")
}
func (UnimplementedEnumServiceServer) UpdateEnum(context.Context, *UpdateEnumRequest) (*UpdateEnumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEnum not implemented")
}
func (UnimplementedEnumServiceServer) mustEmbedUnimplementedEnumServiceServer() {}
func (UnimplementedEnumServiceServer) testEmbeddedByValue()                     {}

// UnsafeEnumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnumServiceServer will
// result in compilation errors.
type UnsafeEnumServiceServer interface {
	mustEmbedUnimplementedEnumServiceServer()
}

func RegisterEnumServiceServer(s grpc.ServiceRegistrar, srv EnumServiceServer) {
	// If the following call pancis, it indicates UnimplementedEnumServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnumService_ServiceDesc, srv)
}

func _EnumService_GetEnums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnumServiceServer).GetEnums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnumService_GetEnums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnumServiceServer).GetEnums(ctx, req.(*GetEnumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnumService_GetEnumById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnumByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnumServiceServer).GetEnumById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnumService_GetEnumById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnumServiceServer).GetEnumById(ctx, req.(*GetEnumByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnumService_UpdateEnum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnumServiceServer).UpdateEnum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnumService_UpdateEnum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnumServiceServer).UpdateEnum(ctx, req.(*UpdateEnumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnumService_ServiceDesc is the grpc.ServiceDesc for EnumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enum.EnumService",
	HandlerType: (*EnumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnums",
			Handler:    _EnumService_GetEnums_Handler,
		},
		{
			MethodName: "GetEnumById",
			Handler:    _EnumService_GetEnumById_Handler,
		},
		{
			MethodName: "UpdateEnum",
			Handler:    _EnumService_UpdateEnum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/master-data/enum/enum.proto",
}
