// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/transaction/absence/absence.proto

package absence

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AbsenceService_GetAbsence_FullMethodName     = "/absence.AbsenceService/GetAbsence"
	AbsenceService_GetAbsenceByID_FullMethodName = "/absence.AbsenceService/GetAbsenceByID"
	AbsenceService_CreateAbsence_FullMethodName  = "/absence.AbsenceService/CreateAbsence"
	AbsenceService_UpdateAbsence_FullMethodName  = "/absence.AbsenceService/UpdateAbsence"
	AbsenceService_DeleteAbsence_FullMethodName  = "/absence.AbsenceService/DeleteAbsence"
)

// AbsenceServiceClient is the client API for AbsenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AbsenceServiceClient interface {
	GetAbsence(ctx context.Context, in *GetAbsenceRequest, opts ...grpc.CallOption) (*GetAbsenceResponse, error)
	GetAbsenceByID(ctx context.Context, in *GetAbsenceByIDRequest, opts ...grpc.CallOption) (*GetAbsenceByIDResponse, error)
	CreateAbsence(ctx context.Context, in *CreateAbsenceRequest, opts ...grpc.CallOption) (*CreateAbsenceResponse, error)
	UpdateAbsence(ctx context.Context, in *UpdateAbsenceRequest, opts ...grpc.CallOption) (*CreateAbsenceResponse, error)
	DeleteAbsence(ctx context.Context, in *DeleteAbsenceRequest, opts ...grpc.CallOption) (*CreateAbsenceResponse, error)
}

type absenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAbsenceServiceClient(cc grpc.ClientConnInterface) AbsenceServiceClient {
	return &absenceServiceClient{cc}
}

func (c *absenceServiceClient) GetAbsence(ctx context.Context, in *GetAbsenceRequest, opts ...grpc.CallOption) (*GetAbsenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAbsenceResponse)
	err := c.cc.Invoke(ctx, AbsenceService_GetAbsence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absenceServiceClient) GetAbsenceByID(ctx context.Context, in *GetAbsenceByIDRequest, opts ...grpc.CallOption) (*GetAbsenceByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAbsenceByIDResponse)
	err := c.cc.Invoke(ctx, AbsenceService_GetAbsenceByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absenceServiceClient) CreateAbsence(ctx context.Context, in *CreateAbsenceRequest, opts ...grpc.CallOption) (*CreateAbsenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAbsenceResponse)
	err := c.cc.Invoke(ctx, AbsenceService_CreateAbsence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absenceServiceClient) UpdateAbsence(ctx context.Context, in *UpdateAbsenceRequest, opts ...grpc.CallOption) (*CreateAbsenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAbsenceResponse)
	err := c.cc.Invoke(ctx, AbsenceService_UpdateAbsence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absenceServiceClient) DeleteAbsence(ctx context.Context, in *DeleteAbsenceRequest, opts ...grpc.CallOption) (*CreateAbsenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAbsenceResponse)
	err := c.cc.Invoke(ctx, AbsenceService_DeleteAbsence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AbsenceServiceServer is the server API for AbsenceService service.
// All implementations must embed UnimplementedAbsenceServiceServer
// for forward compatibility.
type AbsenceServiceServer interface {
	GetAbsence(context.Context, *GetAbsenceRequest) (*GetAbsenceResponse, error)
	GetAbsenceByID(context.Context, *GetAbsenceByIDRequest) (*GetAbsenceByIDResponse, error)
	CreateAbsence(context.Context, *CreateAbsenceRequest) (*CreateAbsenceResponse, error)
	UpdateAbsence(context.Context, *UpdateAbsenceRequest) (*CreateAbsenceResponse, error)
	DeleteAbsence(context.Context, *DeleteAbsenceRequest) (*CreateAbsenceResponse, error)
	mustEmbedUnimplementedAbsenceServiceServer()
}

// UnimplementedAbsenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAbsenceServiceServer struct{}

func (UnimplementedAbsenceServiceServer) GetAbsence(context.Context, *GetAbsenceRequest) (*GetAbsenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAbsence not implemented")
}
func (UnimplementedAbsenceServiceServer) GetAbsenceByID(context.Context, *GetAbsenceByIDRequest) (*GetAbsenceByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAbsenceByID not implemented")
}
func (UnimplementedAbsenceServiceServer) CreateAbsence(context.Context, *CreateAbsenceRequest) (*CreateAbsenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAbsence not implemented")
}
func (UnimplementedAbsenceServiceServer) UpdateAbsence(context.Context, *UpdateAbsenceRequest) (*CreateAbsenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAbsence not implemented")
}
func (UnimplementedAbsenceServiceServer) DeleteAbsence(context.Context, *DeleteAbsenceRequest) (*CreateAbsenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAbsence not implemented")
}
func (UnimplementedAbsenceServiceServer) mustEmbedUnimplementedAbsenceServiceServer() {}
func (UnimplementedAbsenceServiceServer) testEmbeddedByValue()                        {}

// UnsafeAbsenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AbsenceServiceServer will
// result in compilation errors.
type UnsafeAbsenceServiceServer interface {
	mustEmbedUnimplementedAbsenceServiceServer()
}

func RegisterAbsenceServiceServer(s grpc.ServiceRegistrar, srv AbsenceServiceServer) {
	// If the following call pancis, it indicates UnimplementedAbsenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AbsenceService_ServiceDesc, srv)
}

func _AbsenceService_GetAbsence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAbsenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsenceServiceServer).GetAbsence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbsenceService_GetAbsence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsenceServiceServer).GetAbsence(ctx, req.(*GetAbsenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AbsenceService_GetAbsenceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAbsenceByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsenceServiceServer).GetAbsenceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbsenceService_GetAbsenceByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsenceServiceServer).GetAbsenceByID(ctx, req.(*GetAbsenceByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AbsenceService_CreateAbsence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAbsenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsenceServiceServer).CreateAbsence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbsenceService_CreateAbsence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsenceServiceServer).CreateAbsence(ctx, req.(*CreateAbsenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AbsenceService_UpdateAbsence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAbsenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsenceServiceServer).UpdateAbsence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbsenceService_UpdateAbsence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsenceServiceServer).UpdateAbsence(ctx, req.(*UpdateAbsenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AbsenceService_DeleteAbsence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAbsenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsenceServiceServer).DeleteAbsence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbsenceService_DeleteAbsence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsenceServiceServer).DeleteAbsence(ctx, req.(*DeleteAbsenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AbsenceService_ServiceDesc is the grpc.ServiceDesc for AbsenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AbsenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "absence.AbsenceService",
	HandlerType: (*AbsenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAbsence",
			Handler:    _AbsenceService_GetAbsence_Handler,
		},
		{
			MethodName: "GetAbsenceByID",
			Handler:    _AbsenceService_GetAbsenceByID_Handler,
		},
		{
			MethodName: "CreateAbsence",
			Handler:    _AbsenceService_CreateAbsence_Handler,
		},
		{
			MethodName: "UpdateAbsence",
			Handler:    _AbsenceService_UpdateAbsence_Handler,
		},
		{
			MethodName: "DeleteAbsence",
			Handler:    _AbsenceService_DeleteAbsence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction/absence/absence.proto",
}
