// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/transaction/reprimand/reprimand.proto

package reprimand

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReprimandService_GetEmployeeReprimandSummary_FullMethodName      = "/reprimand.ReprimandService/GetEmployeeReprimandSummary"
	ReprimandService_GetEmployeeReprimandList_FullMethodName         = "/reprimand.ReprimandService/GetEmployeeReprimandList"
	ReprimandService_GetEmployeeReprimandDetail_FullMethodName       = "/reprimand.ReprimandService/GetEmployeeReprimandDetail"
	ReprimandService_GetEmployeeReprimandListExport_FullMethodName   = "/reprimand.ReprimandService/GetEmployeeReprimandListExport"
	ReprimandService_GetEmployeeReprimandDetailExport_FullMethodName = "/reprimand.ReprimandService/GetEmployeeReprimandDetailExport"
)

// ReprimandServiceClient is the client API for ReprimandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReprimandServiceClient interface {
	GetEmployeeReprimandSummary(ctx context.Context, in *GetEmployeeReprimandRequest, opts ...grpc.CallOption) (*GetEmployeeReprimandSummaryResponse, error)
	GetEmployeeReprimandList(ctx context.Context, in *GetEmployeeReprimandRequest, opts ...grpc.CallOption) (*GetEmployeeReprimandResponse, error)
	GetEmployeeReprimandDetail(ctx context.Context, in *GetEmployeeReprimandRequest, opts ...grpc.CallOption) (*GetEmployeeReprimandResponse, error)
	GetEmployeeReprimandListExport(ctx context.Context, in *GetEmployeeReprimandRequest, opts ...grpc.CallOption) (*GetEmployeeReprimandExportResponse, error)
	GetEmployeeReprimandDetailExport(ctx context.Context, in *GetEmployeeReprimandRequest, opts ...grpc.CallOption) (*GetEmployeeReprimandExportResponse, error)
}

type reprimandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReprimandServiceClient(cc grpc.ClientConnInterface) ReprimandServiceClient {
	return &reprimandServiceClient{cc}
}

func (c *reprimandServiceClient) GetEmployeeReprimandSummary(ctx context.Context, in *GetEmployeeReprimandRequest, opts ...grpc.CallOption) (*GetEmployeeReprimandSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeReprimandSummaryResponse)
	err := c.cc.Invoke(ctx, ReprimandService_GetEmployeeReprimandSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reprimandServiceClient) GetEmployeeReprimandList(ctx context.Context, in *GetEmployeeReprimandRequest, opts ...grpc.CallOption) (*GetEmployeeReprimandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeReprimandResponse)
	err := c.cc.Invoke(ctx, ReprimandService_GetEmployeeReprimandList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reprimandServiceClient) GetEmployeeReprimandDetail(ctx context.Context, in *GetEmployeeReprimandRequest, opts ...grpc.CallOption) (*GetEmployeeReprimandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeReprimandResponse)
	err := c.cc.Invoke(ctx, ReprimandService_GetEmployeeReprimandDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reprimandServiceClient) GetEmployeeReprimandListExport(ctx context.Context, in *GetEmployeeReprimandRequest, opts ...grpc.CallOption) (*GetEmployeeReprimandExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeReprimandExportResponse)
	err := c.cc.Invoke(ctx, ReprimandService_GetEmployeeReprimandListExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reprimandServiceClient) GetEmployeeReprimandDetailExport(ctx context.Context, in *GetEmployeeReprimandRequest, opts ...grpc.CallOption) (*GetEmployeeReprimandExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeReprimandExportResponse)
	err := c.cc.Invoke(ctx, ReprimandService_GetEmployeeReprimandDetailExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReprimandServiceServer is the server API for ReprimandService service.
// All implementations must embed UnimplementedReprimandServiceServer
// for forward compatibility.
type ReprimandServiceServer interface {
	GetEmployeeReprimandSummary(context.Context, *GetEmployeeReprimandRequest) (*GetEmployeeReprimandSummaryResponse, error)
	GetEmployeeReprimandList(context.Context, *GetEmployeeReprimandRequest) (*GetEmployeeReprimandResponse, error)
	GetEmployeeReprimandDetail(context.Context, *GetEmployeeReprimandRequest) (*GetEmployeeReprimandResponse, error)
	GetEmployeeReprimandListExport(context.Context, *GetEmployeeReprimandRequest) (*GetEmployeeReprimandExportResponse, error)
	GetEmployeeReprimandDetailExport(context.Context, *GetEmployeeReprimandRequest) (*GetEmployeeReprimandExportResponse, error)
	mustEmbedUnimplementedReprimandServiceServer()
}

// UnimplementedReprimandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReprimandServiceServer struct{}

func (UnimplementedReprimandServiceServer) GetEmployeeReprimandSummary(context.Context, *EmptyRequest) (*GetEmployeeReprimandSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmployeeReprimandSummary not implemented")
}
func (UnimplementedReprimandServiceServer) GetEmployeeReprimandList(context.Context, *GetEmployeeReprimandRequest) (*GetEmployeeReprimandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmployeeReprimandList not implemented")
}
func (UnimplementedReprimandServiceServer) GetEmployeeReprimandDetail(context.Context, *GetEmployeeReprimandRequest) (*GetEmployeeReprimandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmployeeReprimandDetail not implemented")
}
func (UnimplementedReprimandServiceServer) GetEmployeeReprimandListExport(context.Context, *GetEmployeeReprimandRequest) (*GetEmployeeReprimandExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmployeeReprimandListExport not implemented")
}
func (UnimplementedReprimandServiceServer) GetEmployeeReprimandDetailExport(context.Context, *GetEmployeeReprimandRequest) (*GetEmployeeReprimandExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmployeeReprimandDetailExport not implemented")
}
func (UnimplementedReprimandServiceServer) mustEmbedUnimplementedReprimandServiceServer() {}
func (UnimplementedReprimandServiceServer) testEmbeddedByValue()                          {}

// UnsafeReprimandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReprimandServiceServer will
// result in compilation errors.
type UnsafeReprimandServiceServer interface {
	mustEmbedUnimplementedReprimandServiceServer()
}

func RegisterReprimandServiceServer(s grpc.ServiceRegistrar, srv ReprimandServiceServer) {
	// If the following call panics, it indicates UnimplementedReprimandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReprimandService_ServiceDesc, srv)
}

func _ReprimandService_GetEmployeeReprimandSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeReprimandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReprimandServiceServer).GetEmployeeReprimandSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReprimandService_GetEmployeeReprimandSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReprimandServiceServer).GetEmployeeReprimandSummary(ctx, req.(*GetEmployeeReprimandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReprimandService_GetEmployeeReprimandList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeReprimandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReprimandServiceServer).GetEmployeeReprimandList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReprimandService_GetEmployeeReprimandList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReprimandServiceServer).GetEmployeeReprimandList(ctx, req.(*GetEmployeeReprimandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReprimandService_GetEmployeeReprimandDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeReprimandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReprimandServiceServer).GetEmployeeReprimandDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReprimandService_GetEmployeeReprimandDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReprimandServiceServer).GetEmployeeReprimandDetail(ctx, req.(*GetEmployeeReprimandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReprimandService_GetEmployeeReprimandListExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeReprimandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReprimandServiceServer).GetEmployeeReprimandListExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReprimandService_GetEmployeeReprimandListExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReprimandServiceServer).GetEmployeeReprimandListExport(ctx, req.(*GetEmployeeReprimandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReprimandService_GetEmployeeReprimandDetailExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeReprimandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReprimandServiceServer).GetEmployeeReprimandDetailExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReprimandService_GetEmployeeReprimandDetailExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReprimandServiceServer).GetEmployeeReprimandDetailExport(ctx, req.(*GetEmployeeReprimandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReprimandService_ServiceDesc is the grpc.ServiceDesc for ReprimandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReprimandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reprimand.ReprimandService",
	HandlerType: (*ReprimandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmployeeReprimandSummary",
			Handler:    _ReprimandService_GetEmployeeReprimandSummary_Handler,
		},
		{
			MethodName: "GetEmployeeReprimandList",
			Handler:    _ReprimandService_GetEmployeeReprimandList_Handler,
		},
		{
			MethodName: "GetEmployeeReprimandDetail",
			Handler:    _ReprimandService_GetEmployeeReprimandDetail_Handler,
		},
		{
			MethodName: "GetEmployeeReprimandListExport",
			Handler:    _ReprimandService_GetEmployeeReprimandListExport_Handler,
		},
		{
			MethodName: "GetEmployeeReprimandDetailExport",
			Handler:    _ReprimandService_GetEmployeeReprimandDetailExport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction/reprimand/reprimand.proto",
}
