// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/transaction/dashboard/dashboard.proto

package dashboard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DashboardService_GetDashboardTotalActive_FullMethodName            = "/dashboard.DashboardService/GetDashboardTotalActive"
	DashboardService_GetDashboardActiveJoinResign_FullMethodName       = "/dashboard.DashboardService/GetDashboardActiveJoinResign"
	DashboardService_GetDashboardAgeInformation_FullMethodName         = "/dashboard.DashboardService/GetDashboardAgeInformation"
	DashboardService_GetDashboardTimeOffTrend_FullMethodName           = "/dashboard.DashboardService/GetDashboardTimeOffTrend"
	DashboardService_GetDashboardJobFamily_FullMethodName              = "/dashboard.DashboardService/GetDashboardJobFamily"
	DashboardService_GetDashboardEmployeeBreakdown_FullMethodName      = "/dashboard.DashboardService/GetDashboardEmployeeBreakdown"
	DashboardService_GetDashboardOvertimeDuration_FullMethodName       = "/dashboard.DashboardService/GetDashboardOvertimeDuration"
	DashboardService_GetDashboardEmployeeTimeOff_FullMethodName        = "/dashboard.DashboardService/GetDashboardEmployeeTimeOff"
	DashboardService_GetDashboardTodayAttendance_FullMethodName        = "/dashboard.DashboardService/GetDashboardTodayAttendance"
	DashboardService_GetDashboardAttendanceRecord_FullMethodName       = "/dashboard.DashboardService/GetDashboardAttendanceRecord"
	DashboardService_GetDashboardDemography_FullMethodName             = "/dashboard.DashboardService/GetDashboardDemography"
	DashboardService_GetDashboardServiceLength_FullMethodName          = "/dashboard.DashboardService/GetDashboardServiceLength"
	DashboardService_GetDashboardDetailEmployeeActive_FullMethodName   = "/dashboard.DashboardService/GetDashboardDetailEmployeeActive"
	DashboardService_GetDashboardDetailOvertimeDuration_FullMethodName = "/dashboard.DashboardService/GetDashboardDetailOvertimeDuration"
	DashboardService_GetDashboardDetailAge_FullMethodName              = "/dashboard.DashboardService/GetDashboardDetailAge"
	DashboardService_GetDashboardDetailAttendance_FullMethodName       = "/dashboard.DashboardService/GetDashboardDetailAttendance"
	DashboardService_GetDashboardDetailTimeOff_FullMethodName          = "/dashboard.DashboardService/GetDashboardDetailTimeOff"
	DashboardService_DownloadAttendanceRecord_FullMethodName           = "/dashboard.DashboardService/DownloadAttendanceRecord"
	DashboardService_DownloadServiceLength_FullMethodName              = "/dashboard.DashboardService/DownloadServiceLength"
	DashboardService_DownloadEmployeeBreakdown_FullMethodName          = "/dashboard.DashboardService/DownloadEmployeeBreakdown"
	DashboardService_DownloadEmployeeTimeOff_FullMethodName            = "/dashboard.DashboardService/DownloadEmployeeTimeOff"
	DashboardService_DownloadJoinResign_FullMethodName                 = "/dashboard.DashboardService/DownloadJoinResign"
	DashboardService_DownloadEmployeeActive_FullMethodName             = "/dashboard.DashboardService/DownloadEmployeeActive"
	DashboardService_GetDownloadLogs_FullMethodName                    = "/dashboard.DashboardService/GetDownloadLogs"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardServiceClient interface {
	GetDashboardTotalActive(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardTotalActiveResponse, error)
	GetDashboardActiveJoinResign(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardActiveJoinResignResponse, error)
	GetDashboardAgeInformation(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardAgeInformationResponse, error)
	GetDashboardTimeOffTrend(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardTimeOffTrendResponse, error)
	GetDashboardJobFamily(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardJobFamilyResponse, error)
	GetDashboardEmployeeBreakdown(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardEmployeeBreakdownResponse, error)
	GetDashboardOvertimeDuration(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardOvertimeDurationResponse, error)
	GetDashboardEmployeeTimeOff(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardEmployeeTimeOffResponse, error)
	GetDashboardTodayAttendance(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardTodayAttendanceResponse, error)
	GetDashboardAttendanceRecord(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardAttendanceRecordResponse, error)
	GetDashboardDemography(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDemographyResponse, error)
	GetDashboardServiceLength(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardServiceLengthResponse, error)
	GetDashboardDetailEmployeeActive(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDetailEmployeeActiveResponse, error)
	GetDashboardDetailOvertimeDuration(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDetailEmployeeActiveResponse, error)
	GetDashboardDetailAge(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDetailEmployeeActiveResponse, error)
	GetDashboardDetailAttendance(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDetailAttendanceResponse, error)
	GetDashboardDetailTimeOff(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDetailTimeOffResponse, error)
	DownloadAttendanceRecord(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	DownloadServiceLength(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	DownloadEmployeeBreakdown(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	DownloadEmployeeTimeOff(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	DownloadJoinResign(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	DownloadEmployeeActive(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	GetDownloadLogs(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDownloadLogsResponse, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) GetDashboardTotalActive(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardTotalActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardTotalActiveResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardTotalActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardActiveJoinResign(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardActiveJoinResignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardActiveJoinResignResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardActiveJoinResign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardAgeInformation(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardAgeInformationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardAgeInformationResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardAgeInformation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardTimeOffTrend(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardTimeOffTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardTimeOffTrendResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardTimeOffTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardJobFamily(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardJobFamilyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardJobFamilyResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardJobFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardEmployeeBreakdown(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardEmployeeBreakdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardEmployeeBreakdownResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardEmployeeBreakdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardOvertimeDuration(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardOvertimeDurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardOvertimeDurationResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardOvertimeDuration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardEmployeeTimeOff(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardEmployeeTimeOffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardEmployeeTimeOffResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardEmployeeTimeOff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardTodayAttendance(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardTodayAttendanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardTodayAttendanceResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardTodayAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardAttendanceRecord(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardAttendanceRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardAttendanceRecordResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardAttendanceRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardDemography(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDemographyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardDemographyResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardDemography_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardServiceLength(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardServiceLengthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardServiceLengthResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardServiceLength_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardDetailEmployeeActive(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDetailEmployeeActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardDetailEmployeeActiveResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardDetailEmployeeActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardDetailOvertimeDuration(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDetailEmployeeActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardDetailEmployeeActiveResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardDetailOvertimeDuration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardDetailAge(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDetailEmployeeActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardDetailEmployeeActiveResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardDetailAge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardDetailAttendance(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDetailAttendanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardDetailAttendanceResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardDetailAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDashboardDetailTimeOff(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardDetailTimeOffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardDetailTimeOffResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardDetailTimeOff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) DownloadAttendanceRecord(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, DashboardService_DownloadAttendanceRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) DownloadServiceLength(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, DashboardService_DownloadServiceLength_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) DownloadEmployeeBreakdown(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, DashboardService_DownloadEmployeeBreakdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) DownloadEmployeeTimeOff(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, DashboardService_DownloadEmployeeTimeOff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) DownloadJoinResign(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, DashboardService_DownloadJoinResign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) DownloadEmployeeActive(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, DashboardService_DownloadEmployeeActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDownloadLogs(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDownloadLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDownloadLogsResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDownloadLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility.
type DashboardServiceServer interface {
	GetDashboardTotalActive(context.Context, *GetDashboardRequest) (*GetDashboardTotalActiveResponse, error)
	GetDashboardActiveJoinResign(context.Context, *GetDashboardRequest) (*GetDashboardActiveJoinResignResponse, error)
	GetDashboardAgeInformation(context.Context, *GetDashboardRequest) (*GetDashboardAgeInformationResponse, error)
	GetDashboardTimeOffTrend(context.Context, *GetDashboardRequest) (*GetDashboardTimeOffTrendResponse, error)
	GetDashboardJobFamily(context.Context, *GetDashboardRequest) (*GetDashboardJobFamilyResponse, error)
	GetDashboardEmployeeBreakdown(context.Context, *GetDashboardRequest) (*GetDashboardEmployeeBreakdownResponse, error)
	GetDashboardOvertimeDuration(context.Context, *GetDashboardRequest) (*GetDashboardOvertimeDurationResponse, error)
	GetDashboardEmployeeTimeOff(context.Context, *GetDashboardRequest) (*GetDashboardEmployeeTimeOffResponse, error)
	GetDashboardTodayAttendance(context.Context, *GetDashboardRequest) (*GetDashboardTodayAttendanceResponse, error)
	GetDashboardAttendanceRecord(context.Context, *GetDashboardRequest) (*GetDashboardAttendanceRecordResponse, error)
	GetDashboardDemography(context.Context, *GetDashboardRequest) (*GetDashboardDemographyResponse, error)
	GetDashboardServiceLength(context.Context, *GetDashboardRequest) (*GetDashboardServiceLengthResponse, error)
	GetDashboardDetailEmployeeActive(context.Context, *GetDashboardRequest) (*GetDashboardDetailEmployeeActiveResponse, error)
	GetDashboardDetailOvertimeDuration(context.Context, *GetDashboardRequest) (*GetDashboardDetailEmployeeActiveResponse, error)
	GetDashboardDetailAge(context.Context, *GetDashboardRequest) (*GetDashboardDetailEmployeeActiveResponse, error)
	GetDashboardDetailAttendance(context.Context, *GetDashboardRequest) (*GetDashboardDetailAttendanceResponse, error)
	GetDashboardDetailTimeOff(context.Context, *GetDashboardRequest) (*GetDashboardDetailTimeOffResponse, error)
	DownloadAttendanceRecord(context.Context, *GetDashboardRequest) (*GetFileResponse, error)
	DownloadServiceLength(context.Context, *GetDashboardRequest) (*GetFileResponse, error)
	DownloadEmployeeBreakdown(context.Context, *GetDashboardRequest) (*GetFileResponse, error)
	DownloadEmployeeTimeOff(context.Context, *GetDashboardRequest) (*GetFileResponse, error)
	DownloadJoinResign(context.Context, *GetDashboardRequest) (*GetFileResponse, error)
	DownloadEmployeeActive(context.Context, *GetDashboardRequest) (*GetFileResponse, error)
	GetDownloadLogs(context.Context, *GetDashboardRequest) (*GetDownloadLogsResponse, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServiceServer struct{}

func (UnimplementedDashboardServiceServer) GetDashboardTotalActive(context.Context, *GetDashboardRequest) (*GetDashboardTotalActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardTotalActive not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardActiveJoinResign(context.Context, *GetDashboardRequest) (*GetDashboardActiveJoinResignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardActiveJoinResign not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardAgeInformation(context.Context, *GetDashboardRequest) (*GetDashboardAgeInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardAgeInformation not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardTimeOffTrend(context.Context, *GetDashboardRequest) (*GetDashboardTimeOffTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardTimeOffTrend not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardJobFamily(context.Context, *GetDashboardRequest) (*GetDashboardJobFamilyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardJobFamily not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardEmployeeBreakdown(context.Context, *GetDashboardRequest) (*GetDashboardEmployeeBreakdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardEmployeeBreakdown not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardOvertimeDuration(context.Context, *GetDashboardRequest) (*GetDashboardOvertimeDurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardOvertimeDuration not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardEmployeeTimeOff(context.Context, *GetDashboardRequest) (*GetDashboardEmployeeTimeOffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardEmployeeTimeOff not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardTodayAttendance(context.Context, *GetDashboardRequest) (*GetDashboardTodayAttendanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardTodayAttendance not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardAttendanceRecord(context.Context, *GetDashboardRequest) (*GetDashboardAttendanceRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardAttendanceRecord not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardDemography(context.Context, *GetDashboardRequest) (*GetDashboardDemographyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardDemography not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardServiceLength(context.Context, *GetDashboardRequest) (*GetDashboardServiceLengthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardServiceLength not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardDetailEmployeeActive(context.Context, *GetDashboardRequest) (*GetDashboardDetailEmployeeActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardDetailEmployeeActive not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardDetailOvertimeDuration(context.Context, *GetDashboardRequest) (*GetDashboardDetailEmployeeActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardDetailOvertimeDuration not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardDetailAge(context.Context, *GetDashboardRequest) (*GetDashboardDetailEmployeeActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardDetailAge not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardDetailAttendance(context.Context, *GetDashboardRequest) (*GetDashboardDetailAttendanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardDetailAttendance not implemented")
}
func (UnimplementedDashboardServiceServer) GetDashboardDetailTimeOff(context.Context, *GetDashboardRequest) (*GetDashboardDetailTimeOffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboardDetailTimeOff not implemented")
}
func (UnimplementedDashboardServiceServer) DownloadAttendanceRecord(context.Context, *GetDashboardRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadAttendanceRecord not implemented")
}
func (UnimplementedDashboardServiceServer) DownloadServiceLength(context.Context, *GetDashboardRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadServiceLength not implemented")
}
func (UnimplementedDashboardServiceServer) DownloadEmployeeBreakdown(context.Context, *GetDashboardRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadEmployeeBreakdown not implemented")
}
func (UnimplementedDashboardServiceServer) DownloadEmployeeTimeOff(context.Context, *GetDashboardRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadEmployeeTimeOff not implemented")
}
func (UnimplementedDashboardServiceServer) DownloadJoinResign(context.Context, *GetDashboardRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadJoinResign not implemented")
}
func (UnimplementedDashboardServiceServer) DownloadEmployeeActive(context.Context, *GetDashboardRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadEmployeeActive not implemented")
}
func (UnimplementedDashboardServiceServer) GetDownloadLogs(context.Context, *GetDashboardRequest) (*GetDownloadLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDownloadLogs not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}
func (UnimplementedDashboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	// If the following call pancis, it indicates UnimplementedDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_GetDashboardTotalActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardTotalActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardTotalActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardTotalActive(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardActiveJoinResign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardActiveJoinResign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardActiveJoinResign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardActiveJoinResign(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardAgeInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardAgeInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardAgeInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardAgeInformation(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardTimeOffTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardTimeOffTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardTimeOffTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardTimeOffTrend(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardJobFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardJobFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardJobFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardJobFamily(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardEmployeeBreakdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardEmployeeBreakdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardEmployeeBreakdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardEmployeeBreakdown(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardOvertimeDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardOvertimeDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardOvertimeDuration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardOvertimeDuration(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardEmployeeTimeOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardEmployeeTimeOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardEmployeeTimeOff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardEmployeeTimeOff(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardTodayAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardTodayAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardTodayAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardTodayAttendance(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardAttendanceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardAttendanceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardAttendanceRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardAttendanceRecord(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardDemography_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardDemography(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardDemography_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardDemography(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardServiceLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardServiceLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardServiceLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardServiceLength(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardDetailEmployeeActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardDetailEmployeeActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardDetailEmployeeActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardDetailEmployeeActive(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardDetailOvertimeDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardDetailOvertimeDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardDetailOvertimeDuration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardDetailOvertimeDuration(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardDetailAge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardDetailAge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardDetailAge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardDetailAge(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardDetailAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardDetailAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardDetailAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardDetailAttendance(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDashboardDetailTimeOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardDetailTimeOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardDetailTimeOff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardDetailTimeOff(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_DownloadAttendanceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).DownloadAttendanceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_DownloadAttendanceRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).DownloadAttendanceRecord(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_DownloadServiceLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).DownloadServiceLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_DownloadServiceLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).DownloadServiceLength(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_DownloadEmployeeBreakdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).DownloadEmployeeBreakdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_DownloadEmployeeBreakdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).DownloadEmployeeBreakdown(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_DownloadEmployeeTimeOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).DownloadEmployeeTimeOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_DownloadEmployeeTimeOff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).DownloadEmployeeTimeOff(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_DownloadJoinResign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).DownloadJoinResign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_DownloadJoinResign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).DownloadJoinResign(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_DownloadEmployeeActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).DownloadEmployeeActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_DownloadEmployeeActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).DownloadEmployeeActive(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDownloadLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDownloadLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDownloadLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDownloadLogs(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardTotalActive",
			Handler:    _DashboardService_GetDashboardTotalActive_Handler,
		},
		{
			MethodName: "GetDashboardActiveJoinResign",
			Handler:    _DashboardService_GetDashboardActiveJoinResign_Handler,
		},
		{
			MethodName: "GetDashboardAgeInformation",
			Handler:    _DashboardService_GetDashboardAgeInformation_Handler,
		},
		{
			MethodName: "GetDashboardTimeOffTrend",
			Handler:    _DashboardService_GetDashboardTimeOffTrend_Handler,
		},
		{
			MethodName: "GetDashboardJobFamily",
			Handler:    _DashboardService_GetDashboardJobFamily_Handler,
		},
		{
			MethodName: "GetDashboardEmployeeBreakdown",
			Handler:    _DashboardService_GetDashboardEmployeeBreakdown_Handler,
		},
		{
			MethodName: "GetDashboardOvertimeDuration",
			Handler:    _DashboardService_GetDashboardOvertimeDuration_Handler,
		},
		{
			MethodName: "GetDashboardEmployeeTimeOff",
			Handler:    _DashboardService_GetDashboardEmployeeTimeOff_Handler,
		},
		{
			MethodName: "GetDashboardTodayAttendance",
			Handler:    _DashboardService_GetDashboardTodayAttendance_Handler,
		},
		{
			MethodName: "GetDashboardAttendanceRecord",
			Handler:    _DashboardService_GetDashboardAttendanceRecord_Handler,
		},
		{
			MethodName: "GetDashboardDemography",
			Handler:    _DashboardService_GetDashboardDemography_Handler,
		},
		{
			MethodName: "GetDashboardServiceLength",
			Handler:    _DashboardService_GetDashboardServiceLength_Handler,
		},
		{
			MethodName: "GetDashboardDetailEmployeeActive",
			Handler:    _DashboardService_GetDashboardDetailEmployeeActive_Handler,
		},
		{
			MethodName: "GetDashboardDetailOvertimeDuration",
			Handler:    _DashboardService_GetDashboardDetailOvertimeDuration_Handler,
		},
		{
			MethodName: "GetDashboardDetailAge",
			Handler:    _DashboardService_GetDashboardDetailAge_Handler,
		},
		{
			MethodName: "GetDashboardDetailAttendance",
			Handler:    _DashboardService_GetDashboardDetailAttendance_Handler,
		},
		{
			MethodName: "GetDashboardDetailTimeOff",
			Handler:    _DashboardService_GetDashboardDetailTimeOff_Handler,
		},
		{
			MethodName: "DownloadAttendanceRecord",
			Handler:    _DashboardService_DownloadAttendanceRecord_Handler,
		},
		{
			MethodName: "DownloadServiceLength",
			Handler:    _DashboardService_DownloadServiceLength_Handler,
		},
		{
			MethodName: "DownloadEmployeeBreakdown",
			Handler:    _DashboardService_DownloadEmployeeBreakdown_Handler,
		},
		{
			MethodName: "DownloadEmployeeTimeOff",
			Handler:    _DashboardService_DownloadEmployeeTimeOff_Handler,
		},
		{
			MethodName: "DownloadJoinResign",
			Handler:    _DashboardService_DownloadJoinResign_Handler,
		},
		{
			MethodName: "DownloadEmployeeActive",
			Handler:    _DashboardService_DownloadEmployeeActive_Handler,
		},
		{
			MethodName: "GetDownloadLogs",
			Handler:    _DashboardService_GetDownloadLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction/dashboard/dashboard.proto",
}
