// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: proto/transaction/employeelocation/employeelocation.proto

package employeelocation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmployeeLocationService_GetEmployeeLocations_FullMethodName      = "/employeelocation.EmployeeLocationService/GetEmployeeLocations"
	EmployeeLocationService_GetEmployeeLocationById_FullMethodName   = "/employeelocation.EmployeeLocationService/GetEmployeeLocationById"
	EmployeeLocationService_GetEmployeeDetailById_FullMethodName     = "/employeelocation.EmployeeLocationService/GetEmployeeDetailById"
	EmployeeLocationService_SyncFaceRecognitionData_FullMethodName   = "/employeelocation.EmployeeLocationService/SyncFaceRecognitionData"
	EmployeeLocationService_GetFaceRecognitionImage_FullMethodName   = "/employeelocation.EmployeeLocationService/GetFaceRecognitionImage"
	EmployeeLocationService_ReSyncFaceRecognitionData_FullMethodName = "/employeelocation.EmployeeLocationService/ReSyncFaceRecognitionData"
)

// EmployeeLocationServiceClient is the client API for EmployeeLocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeLocationServiceClient interface {
	GetEmployeeLocations(ctx context.Context, in *GetEmployeeLocationRequest, opts ...grpc.CallOption) (*GetEmployeeLocationResponse, error)
	GetEmployeeLocationById(ctx context.Context, in *GetEmployeeLocationByIDRequest, opts ...grpc.CallOption) (*GetEmployeeLocationByIDResponse, error)
	GetEmployeeDetailById(ctx context.Context, in *GetEmployeeLocationByIDRequest, opts ...grpc.CallOption) (*GetEmployeeDetailByIDResponse, error)
	SyncFaceRecognitionData(ctx context.Context, in *SyncDataRequest, opts ...grpc.CallOption) (*SyncDataResponse, error)
	GetFaceRecognitionImage(ctx context.Context, in *SyncDataRequest, opts ...grpc.CallOption) (*SyncDataResponse, error)
	ReSyncFaceRecognitionData(ctx context.Context, in *SyncDataRequest, opts ...grpc.CallOption) (*SyncDataResponse, error)
}

type employeeLocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeLocationServiceClient(cc grpc.ClientConnInterface) EmployeeLocationServiceClient {
	return &employeeLocationServiceClient{cc}
}

func (c *employeeLocationServiceClient) GetEmployeeLocations(ctx context.Context, in *GetEmployeeLocationRequest, opts ...grpc.CallOption) (*GetEmployeeLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeLocationResponse)
	err := c.cc.Invoke(ctx, EmployeeLocationService_GetEmployeeLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeLocationServiceClient) GetEmployeeLocationById(ctx context.Context, in *GetEmployeeLocationByIDRequest, opts ...grpc.CallOption) (*GetEmployeeLocationByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeLocationByIDResponse)
	err := c.cc.Invoke(ctx, EmployeeLocationService_GetEmployeeLocationById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeLocationServiceClient) GetEmployeeDetailById(ctx context.Context, in *GetEmployeeLocationByIDRequest, opts ...grpc.CallOption) (*GetEmployeeDetailByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeDetailByIDResponse)
	err := c.cc.Invoke(ctx, EmployeeLocationService_GetEmployeeDetailById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeLocationServiceClient) SyncFaceRecognitionData(ctx context.Context, in *SyncDataRequest, opts ...grpc.CallOption) (*SyncDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDataResponse)
	err := c.cc.Invoke(ctx, EmployeeLocationService_SyncFaceRecognitionData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeLocationServiceClient) GetFaceRecognitionImage(ctx context.Context, in *SyncDataRequest, opts ...grpc.CallOption) (*SyncDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDataResponse)
	err := c.cc.Invoke(ctx, EmployeeLocationService_GetFaceRecognitionImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeLocationServiceClient) ReSyncFaceRecognitionData(ctx context.Context, in *SyncDataRequest, opts ...grpc.CallOption) (*SyncDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDataResponse)
	err := c.cc.Invoke(ctx, EmployeeLocationService_ReSyncFaceRecognitionData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeLocationServiceServer is the server API for EmployeeLocationService service.
// All implementations must embed UnimplementedEmployeeLocationServiceServer
// for forward compatibility.
type EmployeeLocationServiceServer interface {
	GetEmployeeLocations(context.Context, *GetEmployeeLocationRequest) (*GetEmployeeLocationResponse, error)
	GetEmployeeLocationById(context.Context, *GetEmployeeLocationByIDRequest) (*GetEmployeeLocationByIDResponse, error)
	GetEmployeeDetailById(context.Context, *GetEmployeeLocationByIDRequest) (*GetEmployeeDetailByIDResponse, error)
	SyncFaceRecognitionData(context.Context, *SyncDataRequest) (*SyncDataResponse, error)
	GetFaceRecognitionImage(context.Context, *SyncDataRequest) (*SyncDataResponse, error)
	ReSyncFaceRecognitionData(context.Context, *SyncDataRequest) (*SyncDataResponse, error)
	mustEmbedUnimplementedEmployeeLocationServiceServer()
}

// UnimplementedEmployeeLocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmployeeLocationServiceServer struct{}

func (UnimplementedEmployeeLocationServiceServer) GetEmployeeLocations(context.Context, *GetEmployeeLocationRequest) (*GetEmployeeLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeLocations not implemented")
}
func (UnimplementedEmployeeLocationServiceServer) GetEmployeeLocationById(context.Context, *GetEmployeeLocationByIDRequest) (*GetEmployeeLocationByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeLocationById not implemented")
}
func (UnimplementedEmployeeLocationServiceServer) GetEmployeeDetailById(context.Context, *GetEmployeeLocationByIDRequest) (*GetEmployeeDetailByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeDetailById not implemented")
}
func (UnimplementedEmployeeLocationServiceServer) SyncFaceRecognitionData(context.Context, *SyncDataRequest) (*SyncDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncFaceRecognitionData not implemented")
}
func (UnimplementedEmployeeLocationServiceServer) GetFaceRecognitionImage(context.Context, *SyncDataRequest) (*SyncDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFaceRecognitionImage not implemented")
}
func (UnimplementedEmployeeLocationServiceServer) ReSyncFaceRecognitionData(context.Context, *SyncDataRequest) (*SyncDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReSyncFaceRecognitionData not implemented")
}
func (UnimplementedEmployeeLocationServiceServer) mustEmbedUnimplementedEmployeeLocationServiceServer() {
}
func (UnimplementedEmployeeLocationServiceServer) testEmbeddedByValue() {}

// UnsafeEmployeeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeLocationServiceServer will
// result in compilation errors.
type UnsafeEmployeeLocationServiceServer interface {
	mustEmbedUnimplementedEmployeeLocationServiceServer()
}

func RegisterEmployeeLocationServiceServer(s grpc.ServiceRegistrar, srv EmployeeLocationServiceServer) {
	// If the following call pancis, it indicates UnimplementedEmployeeLocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmployeeLocationService_ServiceDesc, srv)
}

func _EmployeeLocationService_GetEmployeeLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeLocationServiceServer).GetEmployeeLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeLocationService_GetEmployeeLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeLocationServiceServer).GetEmployeeLocations(ctx, req.(*GetEmployeeLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeLocationService_GetEmployeeLocationById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeLocationByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeLocationServiceServer).GetEmployeeLocationById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeLocationService_GetEmployeeLocationById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeLocationServiceServer).GetEmployeeLocationById(ctx, req.(*GetEmployeeLocationByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeLocationService_GetEmployeeDetailById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeLocationByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeLocationServiceServer).GetEmployeeDetailById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeLocationService_GetEmployeeDetailById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeLocationServiceServer).GetEmployeeDetailById(ctx, req.(*GetEmployeeLocationByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeLocationService_SyncFaceRecognitionData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeLocationServiceServer).SyncFaceRecognitionData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeLocationService_SyncFaceRecognitionData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeLocationServiceServer).SyncFaceRecognitionData(ctx, req.(*SyncDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeLocationService_GetFaceRecognitionImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeLocationServiceServer).GetFaceRecognitionImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeLocationService_GetFaceRecognitionImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeLocationServiceServer).GetFaceRecognitionImage(ctx, req.(*SyncDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeLocationService_ReSyncFaceRecognitionData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeLocationServiceServer).ReSyncFaceRecognitionData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeLocationService_ReSyncFaceRecognitionData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeLocationServiceServer).ReSyncFaceRecognitionData(ctx, req.(*SyncDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeLocationService_ServiceDesc is the grpc.ServiceDesc for EmployeeLocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeLocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employeelocation.EmployeeLocationService",
	HandlerType: (*EmployeeLocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmployeeLocations",
			Handler:    _EmployeeLocationService_GetEmployeeLocations_Handler,
		},
		{
			MethodName: "GetEmployeeLocationById",
			Handler:    _EmployeeLocationService_GetEmployeeLocationById_Handler,
		},
		{
			MethodName: "GetEmployeeDetailById",
			Handler:    _EmployeeLocationService_GetEmployeeDetailById_Handler,
		},
		{
			MethodName: "SyncFaceRecognitionData",
			Handler:    _EmployeeLocationService_SyncFaceRecognitionData_Handler,
		},
		{
			MethodName: "GetFaceRecognitionImage",
			Handler:    _EmployeeLocationService_GetFaceRecognitionImage_Handler,
		},
		{
			MethodName: "ReSyncFaceRecognitionData",
			Handler:    _EmployeeLocationService_ReSyncFaceRecognitionData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction/employeelocation/employeelocation.proto",
}
