// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/transaction/mcu/mcu.proto

package mcu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	McuService_GetEmployeeMCUSummary_FullMethodName             = "/mcu.McuService/GetEmployeeMCUSummary"
	McuService_GetEmployeeMCUSummaryByEmployeeID_FullMethodName = "/mcu.McuService/GetEmployeeMCUSummaryByEmployeeID"
	McuService_GetEmployeeMCUList_FullMethodName                = "/mcu.McuService/GetEmployeeMCUList"
	McuService_GetEmployeeMCUDetail_FullMethodName              = "/mcu.McuService/GetEmployeeMCUDetail"
	McuService_GetEmployeeMCUListExport_FullMethodName          = "/mcu.McuService/GetEmployeeMCUListExport"
	McuService_GetEmployeeMCUDetailExport_FullMethodName        = "/mcu.McuService/GetEmployeeMCUDetailExport"
)

// McuServiceClient is the client API for McuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type McuServiceClient interface {
	GetEmployeeMCUSummary(ctx context.Context, in *GetEmployeeMCUSummaryRequest, opts ...grpc.CallOption) (*GetEmployeeMCUSummaryResponse, error)
	GetEmployeeMCUSummaryByEmployeeID(ctx context.Context, in *GetEmployeeMCURequest, opts ...grpc.CallOption) (*GetEmployeeMCUSummaryResponse, error)
	GetEmployeeMCUList(ctx context.Context, in *GetEmployeeMCURequest, opts ...grpc.CallOption) (*GetEmployeeMCUResponse, error)
	GetEmployeeMCUDetail(ctx context.Context, in *GetEmployeeMCURequest, opts ...grpc.CallOption) (*GetEmployeeMCUResponse, error)
	GetEmployeeMCUListExport(ctx context.Context, in *GetEmployeeMCURequest, opts ...grpc.CallOption) (*GetEmployeeMCUExportResponse, error)
	GetEmployeeMCUDetailExport(ctx context.Context, in *GetEmployeeMCURequest, opts ...grpc.CallOption) (*GetEmployeeMCUExportResponse, error)
}

type mcuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMcuServiceClient(cc grpc.ClientConnInterface) McuServiceClient {
	return &mcuServiceClient{cc}
}

func (c *mcuServiceClient) GetEmployeeMCUSummary(ctx context.Context, in *GetEmployeeMCUSummaryRequest, opts ...grpc.CallOption) (*GetEmployeeMCUSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeMCUSummaryResponse)
	err := c.cc.Invoke(ctx, McuService_GetEmployeeMCUSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcuServiceClient) GetEmployeeMCUSummaryByEmployeeID(ctx context.Context, in *GetEmployeeMCURequest, opts ...grpc.CallOption) (*GetEmployeeMCUSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeMCUSummaryResponse)
	err := c.cc.Invoke(ctx, McuService_GetEmployeeMCUSummaryByEmployeeID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcuServiceClient) GetEmployeeMCUList(ctx context.Context, in *GetEmployeeMCURequest, opts ...grpc.CallOption) (*GetEmployeeMCUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeMCUResponse)
	err := c.cc.Invoke(ctx, McuService_GetEmployeeMCUList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcuServiceClient) GetEmployeeMCUDetail(ctx context.Context, in *GetEmployeeMCURequest, opts ...grpc.CallOption) (*GetEmployeeMCUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeMCUResponse)
	err := c.cc.Invoke(ctx, McuService_GetEmployeeMCUDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcuServiceClient) GetEmployeeMCUListExport(ctx context.Context, in *GetEmployeeMCURequest, opts ...grpc.CallOption) (*GetEmployeeMCUExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeMCUExportResponse)
	err := c.cc.Invoke(ctx, McuService_GetEmployeeMCUListExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcuServiceClient) GetEmployeeMCUDetailExport(ctx context.Context, in *GetEmployeeMCURequest, opts ...grpc.CallOption) (*GetEmployeeMCUExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeMCUExportResponse)
	err := c.cc.Invoke(ctx, McuService_GetEmployeeMCUDetailExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McuServiceServer is the server API for McuService service.
// All implementations must embed UnimplementedMcuServiceServer
// for forward compatibility.
type McuServiceServer interface {
	GetEmployeeMCUSummary(context.Context, *GetEmployeeMCUSummaryRequest) (*GetEmployeeMCUSummaryResponse, error)
	GetEmployeeMCUSummaryByEmployeeID(context.Context, *GetEmployeeMCURequest) (*GetEmployeeMCUSummaryResponse, error)
	GetEmployeeMCUList(context.Context, *GetEmployeeMCURequest) (*GetEmployeeMCUResponse, error)
	GetEmployeeMCUDetail(context.Context, *GetEmployeeMCURequest) (*GetEmployeeMCUResponse, error)
	GetEmployeeMCUListExport(context.Context, *GetEmployeeMCURequest) (*GetEmployeeMCUExportResponse, error)
	GetEmployeeMCUDetailExport(context.Context, *GetEmployeeMCURequest) (*GetEmployeeMCUExportResponse, error)
	mustEmbedUnimplementedMcuServiceServer()
}

// UnimplementedMcuServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMcuServiceServer struct{}

func (UnimplementedMcuServiceServer) GetEmployeeMCUSummary(context.Context, *GetEmployeeMCUSummaryRequest) (*GetEmployeeMCUSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeMCUSummary not implemented")
}
func (UnimplementedMcuServiceServer) GetEmployeeMCUSummaryByEmployeeID(context.Context, *GetEmployeeMCURequest) (*GetEmployeeMCUSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeMCUSummaryByEmployeeID not implemented")
}
func (UnimplementedMcuServiceServer) GetEmployeeMCUList(context.Context, *GetEmployeeMCURequest) (*GetEmployeeMCUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeMCUList not implemented")
}
func (UnimplementedMcuServiceServer) GetEmployeeMCUDetail(context.Context, *GetEmployeeMCURequest) (*GetEmployeeMCUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeMCUDetail not implemented")
}
func (UnimplementedMcuServiceServer) GetEmployeeMCUListExport(context.Context, *GetEmployeeMCURequest) (*GetEmployeeMCUExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeMCUListExport not implemented")
}
func (UnimplementedMcuServiceServer) GetEmployeeMCUDetailExport(context.Context, *GetEmployeeMCURequest) (*GetEmployeeMCUExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeeMCUDetailExport not implemented")
}
func (UnimplementedMcuServiceServer) mustEmbedUnimplementedMcuServiceServer() {}
func (UnimplementedMcuServiceServer) testEmbeddedByValue()                    {}

// UnsafeMcuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to McuServiceServer will
// result in compilation errors.
type UnsafeMcuServiceServer interface {
	mustEmbedUnimplementedMcuServiceServer()
}

func RegisterMcuServiceServer(s grpc.ServiceRegistrar, srv McuServiceServer) {
	// If the following call pancis, it indicates UnimplementedMcuServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&McuService_ServiceDesc, srv)
}

func _McuService_GetEmployeeMCUSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeMCUSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McuServiceServer).GetEmployeeMCUSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McuService_GetEmployeeMCUSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McuServiceServer).GetEmployeeMCUSummary(ctx, req.(*GetEmployeeMCUSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McuService_GetEmployeeMCUSummaryByEmployeeID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeMCURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McuServiceServer).GetEmployeeMCUSummaryByEmployeeID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McuService_GetEmployeeMCUSummaryByEmployeeID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McuServiceServer).GetEmployeeMCUSummaryByEmployeeID(ctx, req.(*GetEmployeeMCURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McuService_GetEmployeeMCUList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeMCURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McuServiceServer).GetEmployeeMCUList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McuService_GetEmployeeMCUList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McuServiceServer).GetEmployeeMCUList(ctx, req.(*GetEmployeeMCURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McuService_GetEmployeeMCUDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeMCURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McuServiceServer).GetEmployeeMCUDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McuService_GetEmployeeMCUDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McuServiceServer).GetEmployeeMCUDetail(ctx, req.(*GetEmployeeMCURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McuService_GetEmployeeMCUListExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeMCURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McuServiceServer).GetEmployeeMCUListExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McuService_GetEmployeeMCUListExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McuServiceServer).GetEmployeeMCUListExport(ctx, req.(*GetEmployeeMCURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _McuService_GetEmployeeMCUDetailExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeMCURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McuServiceServer).GetEmployeeMCUDetailExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McuService_GetEmployeeMCUDetailExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McuServiceServer).GetEmployeeMCUDetailExport(ctx, req.(*GetEmployeeMCURequest))
	}
	return interceptor(ctx, in, info, handler)
}

// McuService_ServiceDesc is the grpc.ServiceDesc for McuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var McuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcu.McuService",
	HandlerType: (*McuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmployeeMCUSummary",
			Handler:    _McuService_GetEmployeeMCUSummary_Handler,
		},
		{
			MethodName: "GetEmployeeMCUSummaryByEmployeeID",
			Handler:    _McuService_GetEmployeeMCUSummaryByEmployeeID_Handler,
		},
		{
			MethodName: "GetEmployeeMCUList",
			Handler:    _McuService_GetEmployeeMCUList_Handler,
		},
		{
			MethodName: "GetEmployeeMCUDetail",
			Handler:    _McuService_GetEmployeeMCUDetail_Handler,
		},
		{
			MethodName: "GetEmployeeMCUListExport",
			Handler:    _McuService_GetEmployeeMCUListExport_Handler,
		},
		{
			MethodName: "GetEmployeeMCUDetailExport",
			Handler:    _McuService_GetEmployeeMCUDetailExport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction/mcu/mcu.proto",
}
