trigger:
  - none

pool:
  vmImage: ubuntu-20.04
  demands: Limit -equals DisAbleParallel

jobs:
  - job: CalculateVersion
    displayName: Semantic Version
    steps:
      # Checkout with persist credentials
      - checkout: self
        persistCredentials: true
      - bash: |
          git fetch origin --tags
          latestTag=`git describe --tags $(git rev-list --tags --max-count=1)`
          commitHash=`git show-ref --dereference "$latestTag" | cut -d ' ' -f 1`
          check=`git show-ref --tags --dereference | grep "$commitHash" | cut -d ' ' -f2 | cut -d '/' -f3 | tail -n1`

          result=`
          if [[ -z "$check" ]];then
              echo 1.0.0
          else
              if [[ -z $(echo "$check" | grep '+') ]];
              then
                  echo $check | sed 's/\^{}//'
              else
                  echo $(git describe --abbrev=0 --tags)
              fi
          fi
          `
          echo "##vso[task.setvariable variable=gitVersion;]$result"
        name: latestVersion
      - task: PowerShell@2
        displayName: Add git commit message for SemVer
        inputs:
          targetType: inline
          script: |
              $result = "$(gitVersion)"
              $PRbranch = "$(System.PullRequest.SourceBranch)"
              $major, $minor, $patch = $result.Split(".")
              
              if ($PRbranch -match 'major') {
                $nextversion = "$([int]$major+1).$($minor).$($patch)"
                Write-Host "major version : $([int]$major+1).$($minor).$($patch)"
              } elseif ($PRbranch -match 'feature' -or $PRbranch -match 'feat') {
                $nextversion = "$($major).$([int]$minor+1).$($patch)"
                Write-Host "minor version : $($major).$([int]$minor+1).$($patch)"
              } elseif ($PRbranch -match 'hotfix' -or $PRbranch -match 'fix') {
                $nextversion = "$($major).$($minor).$([int]$patch+1)"
                Write-Host "patch version : $($major).$($minor).$([int]$patch+1)"
              } elseif ($PRbranch -match 'bugfix') {
                $nextversion = "$($major).$($minor).$([int]$patch+1)"
                Write-Host "merge from bugfix version : $($major).$($minor).$([int]$patch+1)"
              }
              echo "##vso[task.setvariable variable=SemVer;]$nextversion"
        name: tokenize
      - bash: |
          echo $(System.AccessToken) | az devops login
          az pipelines variable-group variable update --group-id 42 --name gitversion_api_gateway --value $(SemVer) -o yaml
          az devops logout
        displayName: write to variable version git
      - pwsh: |
          Write-Host "##vso[build.updatebuildnumber]$(Semver)"
        displayName: Update Build.BuildNumber
