trigger:
  branches:
    exclude:
      - "*" # Exclude all branch triggers
  tags:
    include:
      - "v*" # Include all tags to trigger the pipeline

# Disable PR triggers
pr: none

pool:
  vmImage: ubuntu-22.04
variables:
  imageRepository: kideco/moyo/service/gateway
  containerRegistry: docker-registry-indika

stages:
  - stage: BuildPush
    jobs:
      - job: BuildAndPushImageDocker
        displayName: Build Image Docker
        steps:
          - task: Docker@2
            displayName: Build Docker
            inputs:
              command: buildAndPush
              containerRegistry: $(containerRegistry)
              repository: $(imageRepository)
              buildContext: $(Build.SourcesDirectory)
              tags: |
                $(Build.SourceBranchName)
