// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/transaction/performance/performance.proto

package performance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PerformanceService_GetEmployeePerformanceSummary_FullMethodName             = "/performance.PerformanceService/GetEmployeePerformanceSummary"
	PerformanceService_GetEmployeePerformanceSummaryByEmployeeID_FullMethodName = "/performance.PerformanceService/GetEmployeePerformanceSummaryByEmployeeID"
	PerformanceService_GetEmployeePerformanceList_FullMethodName                = "/performance.PerformanceService/GetEmployeePerformanceList"
	PerformanceService_GetEmployeePerformanceDetail_FullMethodName              = "/performance.PerformanceService/GetEmployeePerformanceDetail"
	PerformanceService_GetEmployeePerformanceListExport_FullMethodName          = "/performance.PerformanceService/GetEmployeePerformanceListExport"
	PerformanceService_GetEmployeePerformanceDetailExport_FullMethodName        = "/performance.PerformanceService/GetEmployeePerformanceDetailExport"
)

// PerformanceServiceClient is the client API for PerformanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PerformanceServiceClient interface {
	GetEmployeePerformanceSummary(ctx context.Context, in *GetEmployeePerformanceSummaryRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceSummaryResponse, error)
	GetEmployeePerformanceSummaryByEmployeeID(ctx context.Context, in *GetEmployeePerformanceRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceSummaryResponse, error)
	GetEmployeePerformanceList(ctx context.Context, in *GetEmployeePerformanceRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceResponse, error)
	GetEmployeePerformanceDetail(ctx context.Context, in *GetEmployeePerformanceRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceResponse, error)
	GetEmployeePerformanceListExport(ctx context.Context, in *GetEmployeePerformanceRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceExportResponse, error)
	GetEmployeePerformanceDetailExport(ctx context.Context, in *GetEmployeePerformanceRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceExportResponse, error)
}

type performanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPerformanceServiceClient(cc grpc.ClientConnInterface) PerformanceServiceClient {
	return &performanceServiceClient{cc}
}

func (c *performanceServiceClient) GetEmployeePerformanceSummary(ctx context.Context, in *GetEmployeePerformanceSummaryRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeePerformanceSummaryResponse)
	err := c.cc.Invoke(ctx, PerformanceService_GetEmployeePerformanceSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceServiceClient) GetEmployeePerformanceSummaryByEmployeeID(ctx context.Context, in *GetEmployeePerformanceRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeePerformanceSummaryResponse)
	err := c.cc.Invoke(ctx, PerformanceService_GetEmployeePerformanceSummaryByEmployeeID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceServiceClient) GetEmployeePerformanceList(ctx context.Context, in *GetEmployeePerformanceRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeePerformanceResponse)
	err := c.cc.Invoke(ctx, PerformanceService_GetEmployeePerformanceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceServiceClient) GetEmployeePerformanceDetail(ctx context.Context, in *GetEmployeePerformanceRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeePerformanceResponse)
	err := c.cc.Invoke(ctx, PerformanceService_GetEmployeePerformanceDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceServiceClient) GetEmployeePerformanceListExport(ctx context.Context, in *GetEmployeePerformanceRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeePerformanceExportResponse)
	err := c.cc.Invoke(ctx, PerformanceService_GetEmployeePerformanceListExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *performanceServiceClient) GetEmployeePerformanceDetailExport(ctx context.Context, in *GetEmployeePerformanceRequest, opts ...grpc.CallOption) (*GetEmployeePerformanceExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeePerformanceExportResponse)
	err := c.cc.Invoke(ctx, PerformanceService_GetEmployeePerformanceDetailExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PerformanceServiceServer is the server API for PerformanceService service.
// All implementations must embed UnimplementedPerformanceServiceServer
// for forward compatibility.
type PerformanceServiceServer interface {
	GetEmployeePerformanceSummary(context.Context, *GetEmployeePerformanceSummaryRequest) (*GetEmployeePerformanceSummaryResponse, error)
	GetEmployeePerformanceSummaryByEmployeeID(context.Context, *GetEmployeePerformanceRequest) (*GetEmployeePerformanceSummaryResponse, error)
	GetEmployeePerformanceList(context.Context, *GetEmployeePerformanceRequest) (*GetEmployeePerformanceResponse, error)
	GetEmployeePerformanceDetail(context.Context, *GetEmployeePerformanceRequest) (*GetEmployeePerformanceResponse, error)
	GetEmployeePerformanceListExport(context.Context, *GetEmployeePerformanceRequest) (*GetEmployeePerformanceExportResponse, error)
	GetEmployeePerformanceDetailExport(context.Context, *GetEmployeePerformanceRequest) (*GetEmployeePerformanceExportResponse, error)
	mustEmbedUnimplementedPerformanceServiceServer()
}

// UnimplementedPerformanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPerformanceServiceServer struct{}

func (UnimplementedPerformanceServiceServer) GetEmployeePerformanceSummary(context.Context, *GetEmployeePerformanceSummaryRequest) (*GetEmployeePerformanceSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeePerformanceSummary not implemented")
}
func (UnimplementedPerformanceServiceServer) GetEmployeePerformanceSummaryByEmployeeID(context.Context, *GetEmployeePerformanceRequest) (*GetEmployeePerformanceSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeePerformanceSummaryByEmployeeID not implemented")
}
func (UnimplementedPerformanceServiceServer) GetEmployeePerformanceList(context.Context, *GetEmployeePerformanceRequest) (*GetEmployeePerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeePerformanceList not implemented")
}
func (UnimplementedPerformanceServiceServer) GetEmployeePerformanceDetail(context.Context, *GetEmployeePerformanceRequest) (*GetEmployeePerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeePerformanceDetail not implemented")
}
func (UnimplementedPerformanceServiceServer) GetEmployeePerformanceListExport(context.Context, *GetEmployeePerformanceRequest) (*GetEmployeePerformanceExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeePerformanceListExport not implemented")
}
func (UnimplementedPerformanceServiceServer) GetEmployeePerformanceDetailExport(context.Context, *GetEmployeePerformanceRequest) (*GetEmployeePerformanceExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployeePerformanceDetailExport not implemented")
}
func (UnimplementedPerformanceServiceServer) mustEmbedUnimplementedPerformanceServiceServer() {}
func (UnimplementedPerformanceServiceServer) testEmbeddedByValue()                            {}

// UnsafePerformanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PerformanceServiceServer will
// result in compilation errors.
type UnsafePerformanceServiceServer interface {
	mustEmbedUnimplementedPerformanceServiceServer()
}

func RegisterPerformanceServiceServer(s grpc.ServiceRegistrar, srv PerformanceServiceServer) {
	// If the following call pancis, it indicates UnimplementedPerformanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PerformanceService_ServiceDesc, srv)
}

func _PerformanceService_GetEmployeePerformanceSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeePerformanceSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceService_GetEmployeePerformanceSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceSummary(ctx, req.(*GetEmployeePerformanceSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceService_GetEmployeePerformanceSummaryByEmployeeID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeePerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceSummaryByEmployeeID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceService_GetEmployeePerformanceSummaryByEmployeeID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceSummaryByEmployeeID(ctx, req.(*GetEmployeePerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceService_GetEmployeePerformanceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeePerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceService_GetEmployeePerformanceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceList(ctx, req.(*GetEmployeePerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceService_GetEmployeePerformanceDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeePerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceService_GetEmployeePerformanceDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceDetail(ctx, req.(*GetEmployeePerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceService_GetEmployeePerformanceListExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeePerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceListExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceService_GetEmployeePerformanceListExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceListExport(ctx, req.(*GetEmployeePerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PerformanceService_GetEmployeePerformanceDetailExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeePerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceDetailExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PerformanceService_GetEmployeePerformanceDetailExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerformanceServiceServer).GetEmployeePerformanceDetailExport(ctx, req.(*GetEmployeePerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PerformanceService_ServiceDesc is the grpc.ServiceDesc for PerformanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PerformanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "performance.PerformanceService",
	HandlerType: (*PerformanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmployeePerformanceSummary",
			Handler:    _PerformanceService_GetEmployeePerformanceSummary_Handler,
		},
		{
			MethodName: "GetEmployeePerformanceSummaryByEmployeeID",
			Handler:    _PerformanceService_GetEmployeePerformanceSummaryByEmployeeID_Handler,
		},
		{
			MethodName: "GetEmployeePerformanceList",
			Handler:    _PerformanceService_GetEmployeePerformanceList_Handler,
		},
		{
			MethodName: "GetEmployeePerformanceDetail",
			Handler:    _PerformanceService_GetEmployeePerformanceDetail_Handler,
		},
		{
			MethodName: "GetEmployeePerformanceListExport",
			Handler:    _PerformanceService_GetEmployeePerformanceListExport_Handler,
		},
		{
			MethodName: "GetEmployeePerformanceDetailExport",
			Handler:    _PerformanceService_GetEmployeePerformanceDetailExport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction/performance/performance.proto",
}
